category={
    'Academic librarian',
'Accountant',
'Accounting technician',
'Actor',
'Actuary',
'Administrative Assistant/Secretary',
'Adult nurse',
'Advertising',
'Advertising account executive',
'Advertising account planner',
'Advertising copywriter',
'Advice worker',
'Advocate (Scotland)',
'Aeronautical engineer',
'Agricultural consultant',
'Agricultural manager',
'Aid worker/humanitarian worker',
'Air traffic controller',
'Aircraft Mechanic',
'Airline cabin crew',
'Airline Pilot',
'Amenity horticulturist',
'Analytical chemist',
'Animal Careers',
'Animal nutritionist',
'Animator',
'Archaeologist',
'Architect',
'Architectural technologist',
'Archivist',
'Armed forces officer',
'Aromatherapist',
'Art Appraiser',
'Art Auctioneer',
'Art therapist',
'Artist',
'Arts administrator',
'Auditor',
'Automotive engineer',
'Back End Developer',
'Bank Teller',
'Barrister',
'BarristerÎ“Ã‡Ã–s clerk',
'Bid manager',
'Bilingual secretary',
'Biomedical engineer',
'Biomedical scientist',
'Biotechnologist',
'Book Publishing',
'Border Control Agent',
'Border force officer',
'Brand manager',
'Broadcasting presenter',
'Building control officer/surveyor',
'Building services engineer',
'Building surveyor',
'Business analyst',
'Call Center',
'Camera operator',
'Careers adviser',
'Careers adviser (higher education)',
'Careers consultant',
'Cartographer',
'Catering manager',
'Charities administrator',
'Charities fundraiser',
'Chemical (process) engineer',
'Chief Operating Officer',
'Child psychotherapist',
'Chiropractor',
'City Manager',
'Civil engineer',
'Civil Service administrator',
'Clinical biochemist',
'Clinical cytogeneticist',
'Clinical microbiologist',
'Clinical molecular geneticist',
'Clinical research associate',
'Clinical scientist - tissue typing',
'Clothing and textile technologist',
'College Professor',
'Colour technologist',
'Commercial airline pilot',
'Commercial horticulturist',
'Commercial/residential/rural surveyor',
'Commissioning editor',
'Commissioning engineer',
'Commodity broker',
'Communications engineer',
'Community arts worker',
'Community education officer',
'Community worker',
'Company secretary',
'Computer Programmer',
'Computer sales support',
'Computer scientist',
'Computer Systems Administrator',
'Conference organiser',
'Consultant',
'Control and instrumentation engineer',
'Corporate banker',
'Corporate treasurer',
'Correctional Officer',
'Counsellor',
'Court reporter/verbatim reporter',
'Credit analyst',
'Criminal Justice',
'Crown Prosecution Service lawyer',
'Crystallographer',
'Curator',
'Customs officer',
'Cyber security specialist',
'Dance movement psychotherapist',
'Data analyst',
'Data scientist',
'Data visualisation analyst',
'Database administrator',
'Database Administrator',
'DCIS Special Agent',
'Debt/finance adviser',
'Dental hygienist',
'Dentist',
'Design engineer',
'Design manager (construction)',
'DevOps engineer',
'Dietitian',
'Diplomatic service',
'Doctor (general practitioner, GP)',
'Doctor (hospital)',
'Dramatherapist',
'Economist',
'Editorial assistant',
'Education administrator',
'Electrical engineer',
'Electronics engineer',
'Energy conservation officer',
'Energy consultant',
'Engineering geologist',
'Environmental education officer',
'Environmental health officer',
'Environmental manager',
'Environmental scientist',
'Equal opportunities officer',
'Equality and diversity officer',
'Ergonomist',
'Estate agent',
'Estimator',
'Exhibition display designer',
'Exhibition organiser',
'Exploration geologist',
'Facilities manager',
'FBI Special Agent',
'Federal Air Marshall',
'Federal Law Enforcement',
'Field trials officer',
'Financial Advisor',
'Financial manager',
'Fire engineer',
'Firefighter',
'Fish and Game Warden',
'Fisheries enforcement officer',
'Fitness centre manager',
'Flight Attendant',
'Food scientist',
'Food technologist',
'Forensic Psychologist',
'Forensic scientist',
'Freelance Writer',
'Freight forwarder',
'Fundraiser',
'Geneticist',
'Geographical information systems manager',
'Geomatics/land surveyor',
'Government Jobs',
'Government lawyer',
'Government research officer',
'Graphic designer',
'Hair Stylist',
'Health and safety adviser',
'Health and safety inspector',
'Health promotion specialist',
'Health service manager',
'Health visitor',
'Herbalist',
'Heritage manager',
'Higher education administrator',
'Higher education advice worker',
'Homeless support worker',
'Horticultural consultant',
'Hospitalist',
'Hotel manager',
'Housing adviser',
'Human Resources',
'Human resources officer',
'Hydrologist',
'ICE Agent',
'Illustrator',
'Immigration officer',
'Immunologist',
'Industrial/product designer',
'Information scientist',
'Information systems manager',
'Information technology/software trainers',
'Insurance Agent',
'Insurance broker',
'Insurance claims inspector',
'Insurance risk surveyor',
'Insurance underwriter',
'Interpreter',
'Investment analyst',
'Investment Banker',
'Investment banker - corporate finance',
'Investment banker Î“Ã‡Ã´ operations',
'Investment fund manager',
'IT consultant',
'IT support analyst',
'Journalist',
'K-9 Police Officer',
'Laboratory technician',
'Land-based engineer',
'Landscape architect',
'Lawyer',
'Learning disability nurse',
'Learning mentor',
'Lecturer (adult education)',
'Lecturer (further education)',
'Lecturer (higher education)',
'Legal executive',
'Leisure centre manager',
'Licensed conveyancer',
'Local government administrator',
'Local government lawyer',
'Logistics/distribution manager',
'Magazine features editor',
'Magazine journalist',
'Maintenance engineer',
'Management',
'Management accountant',
'Manufacturing engineer',
'Manufacturing machine operator',
'Manufacturing toolmaker',
'Marine scientist',
'Market research analyst',
'Market Research Analyst',
'Market research executive',
'Marketing assistant',
'Marketing executive',
'Marketing manager (direct)',
'Marketing manager (social media)',
'Materials engineer',
'Materials specialist',
'Mechanical engineer',
'Media analyst',
'Media buyer',
'Media planner',
'Medical physicist',
'Medical representative',
'Mental Health Counselor',
'Mental health nurse',
'Metallurgist',
'Meteorologist',
'Microbiologist',
'Midwife',
'Military Careers',
'Mining engineer',
'Mobile developer',
'Multimedia programmer',
'Multimedia specialists',
'Museum education officer',
'Museum Jobs',
'Museum/gallery exhibition officer',
'Music Conductor',
'Music Teacher',
'Music therapist',
'Nanoscientist',
'Nature conservation officer',
'Naval architect',
'Network administrator',
'Nurse',
'Nutritional therapist',
'Nutritionist',
'Occupational therapist',
'Oceanographer',
'Office manager',
'Operational researcher',
'Orthodontist',
'Orthoptist',
'Outdoor pursuits manager',
'Packaging technologist',
'Paramedic',
'Patent attorney',
'Patent examiner',
'Pediatrician',
'Pension scheme manager',
'Personal assistant',
'Personal Fitness Trainer',
'Petroleum engineer',
'Pharmacist',
'Pharmacologist',
'Pharmacovigilance officer',
'Photographer',
'Physician Assistant',
'Physiotherapist',
'Picture researcher',
'Planning and development surveyor',
'Planning technician',
'Plant breeder',
'Police Dispatcher',
'Police Officer',
'Political party agent',
'Political researcher',
'Practice nurse',
'Press photographer',
'Press sub-editor',
'Prison officer',
'Private music teacher',
'Probation officer',
'Product development scientist',
'Production manager',
'Programme researcher',
'Programmer',
'Project manager',
'Psychiatrist',
'Psychologist (clinical)s',
'Psychologist (educational)',
'Psychotherapist',
'Public affairs consultant (lobbyist)',
'Public affairs consultant (research)',
'Public house manager',
'Public librarian',
'Public Relations',
'Public relations (PR) officer',
'QA analyst',
'Quality assurance manager',
'Quantity surveyor',
'Records manager',
'Recruitment consultant',
'Recycling officer',
'Regulatory affairs officer',
'Research chemist',
'Research scientist',
'Restaurant manager',
'Retail',
'Retail banker',
'Retail buyer',
'Retail manager',
'Retail merchandiser',
'Retail pharmacist',
'Sales',
'Sales executive',
'Scene of crime officer',
'School Jobs',
'Secretary',
'Seismic interpreter',
'Site engineer',
'Site manager',
'Social researcher',
'Social worker',
'Software Developer',
'Software engineer',
'Soil scientist',
'Solicitor',
'Speech and language therapist',
'Sports coach',
'Sports development officer',
'Sports therapist',
'State Trooper',
'Statistician',
'STEM CareersGeeks',
'Stockbroker',
'Structural engineer',
'Substitute Teacher',
'Systems analyst',
'Systems developer',
'Tax inspector',
'Teacher',
'Teacher (nursery/early years)',
'Teacher (primary)',
'Teacher (secondary)',
'Teacher (special educational needs)',
'Teaching Abroad',
'Teaching Online',
'Teaching/classroom assistant',
'Technical author',
'Technical sales engineer',
'TEFL/TESL teacher',
'Television production assistant',
'Test automation developer',
'Tour guide',
'Tour operator',
'Tour/holiday representative',
'Tourism officer',
'Tourist information manager',
'Town and country planner',
'Toxicologist',
'Trade union official',
'Trade union research officer',
'Trader',
'Trading standards officer',
'Training and development officer',
'Translator',
'Transportation planner',
'Transportation Security Officer',
'Travel agent',
'TV/film/theatre set designer',
'Uniformed Secret Service Officer',
'UX designer',
'Validation engineer',
'Veterinarian',
'Veterinary nurse',
'Veterinary surgeon',
'Video game designer',
'Video game developer',
'Volunteer work organiser',
'Waiter',
'Warehouse manager',
'Waste management officer',
'Water conservation officer',
'Water engineer',
'Web designer',
'Web Developer',
'Wedding Planner',
'Welfare rights adviser',
'Writer',
'Writer/Editor',
'Youth worker',
}
