# Generated by Django 3.1.6 on 2021-02-25 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210225_1829'),
        ('gearupjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rating', models.PositiveIntegerField(default=0)),
                ('number_of_rating', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='accounts.company')),
            ],
        ),
    ]
