# Generated by Django 3.1.6 on 2021-02-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gearupjob', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
