# Generated by Django 3.1.6 on 2021-02-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210225_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number_of_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='company',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seeker',
            name='not_rated',
            field=models.BooleanField(default=True),
        ),
    ]
