# Generated by Django 3.1.6 on 2021-02-27 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210225_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('seeker_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='accounts.seeker')),
            ],
        ),
    ]
